// @generated by api_gen - DO NOT EDIT. Regenerate with scripts/gen_bindings.sh.

#pragma once

#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <flowi/core/string.h>

#define RP_PLUGIN_ABI_VERSION 1
#define RP_EMU_MAX_PLAYERS 4

#ifdef __cplusplus
extern "C" {
#endif

// Framebuffer pixel format.
typedef enum RpPixelFormat {
    // 32-bit, 0xAARRGGBB (alpha ignored).
    RpPixelFormat_Xrgb8888 = 0,
    // 16-bit, native endian.
    RpPixelFormat_Rgb565 = 1,
} RpPixelFormat;

// The abstract controller a core sees, independent of the physical pad the host
// read it from. `Count` is the array-size sentinel and doubles as "this host
// button has no core equivalent".
typedef enum RpEmuButton {
    RpEmuButton_Up = 0,
    RpEmuButton_Down = 1,
    RpEmuButton_Left = 2,
    RpEmuButton_Right = 3,
    // Primary action.
    RpEmuButton_A = 4,
    // Secondary action.
    RpEmuButton_B = 5,
    RpEmuButton_X = 6,
    RpEmuButton_Y = 7,
    // Left shoulder.
    RpEmuButton_L = 8,
    // Right shoulder.
    RpEmuButton_R = 9,
    RpEmuButton_Select = 10,
    RpEmuButton_Start = 11,
    RpEmuButton_Count = 12,
} RpEmuButton;

// Where a core is in its lifecycle.
typedef enum RpEmuLifecycleState {
    // Not loaded.
    RpEmuLifecycleState_Idle = 0,
    // Loading.
    RpEmuLifecycleState_Launching = 1,
    // Actively running.
    RpEmuLifecycleState_Running = 2,
    // Paused.
    RpEmuLifecycleState_Paused = 3,
    // Shutting down.
    RpEmuLifecycleState_Stopping = 4,
    // Error state.
    RpEmuLifecycleState_Error = 5,
    // The current media finished playing naturally (song ended, image display
    // done). The core is still loaded and ready for new media via mount_media,
    // so the frontend can transition seamlessly or stop the core.
    RpEmuLifecycleState_MediaFinished = 6,
} RpEmuLifecycleState;

// Replay's emulator plugin ABI — the vtable a plugin exports and everything its
// slots exchange. Inspired by libretro but tailored to this frontend: emulator
// plugins are dynamically loaded libraries emulating one system each (Amiga,
// C64, NES, Genesis, ...).
//
// The host drives a plugin; a plugin never calls back into the host. The
// visibility macro for the entry point lives in the hand-written
// <replay/emu_plugin.h>.
// One monotonic number for the emulator plugin SDK - these headers and the host
// symbols they declare, nothing else of the host - bumped when any of it changes.
// See <replay/emu_plugin.h> for the gate.
// Maximum number of players routed to a core. Players 0-3 map to physical
// gamepads 0-3.
// The arena a core allocates its instance state from.
typedef struct FlArena FlArena;

typedef struct RpEmuAPI RpEmuAPI;

// The entry point a core library exports, named rp_emu_plugin_get.
typedef const RpEmuAPI* (*RpEmuPluginGetFunc)(void);

// What a loaded core says about itself. The strings are the core's own and stay
// valid as long as it is loaded.
typedef struct RpEmuInfo {
    // "vAmiga", "Vice C64", etc.
    const char* emu_name;
    // "4.4".
    const char* emu_version;
    // "Amiga 500", "Commodore 64", etc.
    const char* system_name;
    // "adf|adz|dms|hdf", pipe-separated.
    const char* supported_extensions;
    // True if a ROM/BIOS is required.
    bool requires_bios;
} RpEmuInfo;

// A core's video output format, including the visible area within the frame
// buffer. An all-zero visible rect means the whole buffer is visible.
typedef struct RpVideoSpec {
    // Frame buffer width in pixels.
    uint32_t width;
    // Frame buffer height in pixels.
    uint32_t height;
    // Pixel format.
    RpPixelFormat pixel_format;
    // Nominal frames per second, e.g. 50.0 for PAL.
    float fps;
    // X offset of the visible area.
    uint32_t visible_x;
    // Y offset of the visible area.
    uint32_t visible_y;
    // Width of the visible area.
    uint32_t visible_width;
    // Height of the visible area.
    uint32_t visible_height;
} RpVideoSpec;

// A core's audio output format.
typedef struct RpAudioSpec {
    // Sample rate, e.g. 44100.
    uint32_t sample_rate;
    // Number of channels (1 = mono, 2 = stereo).
    uint32_t channels;
} RpAudioSpec;

// One player's gamepad button states, indexed by RpEmuButton. The array length
// is RpEmuButton_Count, spelled as a literal because the IDL has no
// constant-resolution pass; <replay/emu_plugin.h> asserts the two agree.
typedef struct RpEmuPlayerInput {
    // Button states for this player's gamepad.
    bool buttons[12];
} RpEmuPlayerInput;

// The full per-frame input snapshot the frontend sends a core. `players[0]`
// mirrors the legacy `buttons` view, so a single-pad core that only reads
// `buttons` keeps working while a multiplayer core reads players[1..3].
typedef struct RpEmuInputState {
    // Player 0 button states (legacy view; mirrors players[0].buttons).
    bool buttons[12];
    // Mouse X delta.
    int16_t mouse_x;
    // Mouse Y delta.
    int16_t mouse_y;
    // Mouse left button.
    bool mouse_left;
    // Mouse right button.
    bool mouse_right;
    // Keyboard state, indexed by scan code.
    bool keyboard_keys[256];
    // Per-player gamepad input for players 0-3. Appended last to keep the
    // layout compatible with cores built before it existed.
    RpEmuPlayerInput players[4];
} RpEmuInputState;

// The per-frame in/out block passed to run_frame: input from the frontend,
// video and audio filled in by the core.
typedef struct RpEmuFrameContext {
    // Input, provided by the frontend.
    const RpEmuInputState* input;
    // Video framebuffer, read-only for the frontend.
    const void* video_buffer;
    // Bytes per scanline.
    uint32_t video_pitch;
    // Frame width in pixels (0 = use the video spec).
    uint32_t video_width;
    // Frame height in pixels (0 = use the video spec).
    uint32_t video_height;
    // Audio samples, interleaved stereo float.
    const float* audio_buffer;
    // Number of audio frames (1 frame = all channels).
    uint32_t audio_frames;
    // Time since the last frame, in seconds.
    double delta_time;
    // True while the core is fast-forwarding; the frontend skips frame pacing.
    bool skip_frame_pacing;
} RpEmuFrameContext;

// The functions a core exports. Slots documented as optional may be nullptr.
typedef struct RpEmuAPI {
    // Report the core's identity; called once during plugin discovery.
    void (*get_info)(RpEmuInfo* info);
    // Create a core instance, allocating from `arena` and loading a BIOS if one
    // is needed. Returns nullptr on failure.
    void* (*create)(FlArena* arena);
    // Destroy an instance and free its resources.
    void (*destroy)(void* core_instance);
    // Mount media from a file path (disk image, ROM, cartridge, ...). The core
    // picks the slot, e.g. DF0 for Amiga floppies; for explicit slot control
    // use set_config_string with slot-specific keys. False on error.
    bool (*mount_media)(void* core_instance, const char* path);
    // Unmount the currently mounted media.
    void (*unmount_media)(void* core_instance);
    // Mount several media files at once for multi-disk content, `count` paths
    // long. The core manages the disk list and offers swapping through its own
    // OSD; for Amiga the first disk boots from DF0. True if at least the first
    // disk mounted. Optional — a null slot means fall back to mount_media()
    // with the first path.
    bool (*mount_media_list)(void* core_instance, const FlString* paths, uint32_t count);
    // Run one frame of emulation into `ctx`.
    void (*run_frame)(void* core_instance, RpEmuFrameContext* ctx);
    // Soft-reset the emulated system.
    void (*reset)(void* core_instance);
    // Hard reset, like power cycling.
    void (*hard_reset)(void* core_instance);
    // Report the current video specification.
    void (*get_video_spec)(void* core_instance, RpVideoSpec* spec);
    // Report the current audio specification.
    void (*get_audio_spec)(void* core_instance, RpAudioSpec* spec);
    // Report the current lifecycle state.
    RpEmuLifecycleState (*get_state)(void* core_instance);
    // Copy up to `frame_count` interleaved float frames into `buffer`, called
    // from the audio thread; returns how many were actually copied. Optional —
    // a null slot means the core pushes audio through RpEmuFrameContext.
    uint32_t (*copy_audio)(void* core_instance, float* buffer, uint32_t frame_count);
    // Serialize state into `buffer`, returning the serialized size or 0 on
    // error; a null `buffer` returns the size required. Optional.
    size_t (*serialize)(void* core_instance, void* buffer, size_t buffer_size);
    // Restore state from `buffer`. Optional.
    bool (*deserialize)(void* core_instance, const void* buffer, size_t buffer_size);
    // Apply a configuration bitmask to a running core (FPGA cores), in the same
    // format as the launch config. Called when the user changes options in the
    // OSD; only options marked runtime-modifiable should take effect. Optional.
    void (*set_config_bitmask)(void* core_instance, uint32_t config_value);
    // Apply one typed configuration option by key (software cores like vAmiga),
    // e.g. "CPU.OVERCLOCKING" or "MEM.CHIP_RAM". Called when the user changes
    // an option in the OSD; only options marked runtime-modifiable should take
    // effect. Optional.
    void (*set_config_int)(void* core_instance, FlString key, int32_t value);
    void (*set_config_float)(void* core_instance, FlString key, float value);
    void (*set_config_bool)(void* core_instance, FlString key, bool value);
    void (*set_config_string)(void* core_instance, FlString key, FlString value);
    // Read back a string configuration value, e.g. the inserted disk path.
    // Returns an empty string for an unset or unknown key. Optional.
    FlString (*get_config_string)(void* core_instance, FlString key);
} RpEmuAPI;

// Layout pins - the IDL-computed layout of the types above,
// checked against what this compiler produces.
static_assert(sizeof(RpEmuInfo) == 40, "RpEmuInfo size drift");
static_assert(offsetof(RpEmuInfo, emu_name) == 0, "RpEmuInfo.emu_name offset drift");
static_assert(offsetof(RpEmuInfo, emu_version) == 8, "RpEmuInfo.emu_version offset drift");
static_assert(offsetof(RpEmuInfo, system_name) == 16, "RpEmuInfo.system_name offset drift");
static_assert(offsetof(RpEmuInfo, supported_extensions) == 24, "RpEmuInfo.supported_extensions offset drift");
static_assert(offsetof(RpEmuInfo, requires_bios) == 32, "RpEmuInfo.requires_bios offset drift");
static_assert(sizeof(RpVideoSpec) == 32, "RpVideoSpec size drift");
static_assert(offsetof(RpVideoSpec, width) == 0, "RpVideoSpec.width offset drift");
static_assert(offsetof(RpVideoSpec, height) == 4, "RpVideoSpec.height offset drift");
static_assert(offsetof(RpVideoSpec, pixel_format) == 8, "RpVideoSpec.pixel_format offset drift");
static_assert(offsetof(RpVideoSpec, fps) == 12, "RpVideoSpec.fps offset drift");
static_assert(offsetof(RpVideoSpec, visible_x) == 16, "RpVideoSpec.visible_x offset drift");
static_assert(offsetof(RpVideoSpec, visible_y) == 20, "RpVideoSpec.visible_y offset drift");
static_assert(offsetof(RpVideoSpec, visible_width) == 24, "RpVideoSpec.visible_width offset drift");
static_assert(offsetof(RpVideoSpec, visible_height) == 28, "RpVideoSpec.visible_height offset drift");
static_assert(sizeof(RpAudioSpec) == 8, "RpAudioSpec size drift");
static_assert(offsetof(RpAudioSpec, sample_rate) == 0, "RpAudioSpec.sample_rate offset drift");
static_assert(offsetof(RpAudioSpec, channels) == 4, "RpAudioSpec.channels offset drift");
static_assert(sizeof(RpEmuPlayerInput) == 12, "RpEmuPlayerInput size drift");
static_assert(offsetof(RpEmuPlayerInput, buttons) == 0, "RpEmuPlayerInput.buttons offset drift");
static_assert(sizeof(RpEmuInputState) == 322, "RpEmuInputState size drift");
static_assert(offsetof(RpEmuInputState, buttons) == 0, "RpEmuInputState.buttons offset drift");
static_assert(offsetof(RpEmuInputState, mouse_x) == 12, "RpEmuInputState.mouse_x offset drift");
static_assert(offsetof(RpEmuInputState, mouse_y) == 14, "RpEmuInputState.mouse_y offset drift");
static_assert(offsetof(RpEmuInputState, mouse_left) == 16, "RpEmuInputState.mouse_left offset drift");
static_assert(offsetof(RpEmuInputState, mouse_right) == 17, "RpEmuInputState.mouse_right offset drift");
static_assert(offsetof(RpEmuInputState, keyboard_keys) == 18, "RpEmuInputState.keyboard_keys offset drift");
static_assert(offsetof(RpEmuInputState, players) == 274, "RpEmuInputState.players offset drift");
static_assert(sizeof(RpEmuFrameContext) == 64, "RpEmuFrameContext size drift");
static_assert(offsetof(RpEmuFrameContext, input) == 0, "RpEmuFrameContext.input offset drift");
static_assert(offsetof(RpEmuFrameContext, video_buffer) == 8, "RpEmuFrameContext.video_buffer offset drift");
static_assert(offsetof(RpEmuFrameContext, video_pitch) == 16, "RpEmuFrameContext.video_pitch offset drift");
static_assert(offsetof(RpEmuFrameContext, video_width) == 20, "RpEmuFrameContext.video_width offset drift");
static_assert(offsetof(RpEmuFrameContext, video_height) == 24, "RpEmuFrameContext.video_height offset drift");
static_assert(offsetof(RpEmuFrameContext, audio_buffer) == 32, "RpEmuFrameContext.audio_buffer offset drift");
static_assert(offsetof(RpEmuFrameContext, audio_frames) == 40, "RpEmuFrameContext.audio_frames offset drift");
static_assert(offsetof(RpEmuFrameContext, delta_time) == 48, "RpEmuFrameContext.delta_time offset drift");
static_assert(offsetof(RpEmuFrameContext, skip_frame_pacing) == 56, "RpEmuFrameContext.skip_frame_pacing offset drift");
static_assert(sizeof(RpEmuAPI) == 168, "RpEmuAPI size drift");
static_assert(offsetof(RpEmuAPI, get_info) == 0, "RpEmuAPI.get_info offset drift");
static_assert(offsetof(RpEmuAPI, create) == 8, "RpEmuAPI.create offset drift");
static_assert(offsetof(RpEmuAPI, destroy) == 16, "RpEmuAPI.destroy offset drift");
static_assert(offsetof(RpEmuAPI, mount_media) == 24, "RpEmuAPI.mount_media offset drift");
static_assert(offsetof(RpEmuAPI, unmount_media) == 32, "RpEmuAPI.unmount_media offset drift");
static_assert(offsetof(RpEmuAPI, mount_media_list) == 40, "RpEmuAPI.mount_media_list offset drift");
static_assert(offsetof(RpEmuAPI, run_frame) == 48, "RpEmuAPI.run_frame offset drift");
static_assert(offsetof(RpEmuAPI, reset) == 56, "RpEmuAPI.reset offset drift");
static_assert(offsetof(RpEmuAPI, hard_reset) == 64, "RpEmuAPI.hard_reset offset drift");
static_assert(offsetof(RpEmuAPI, get_video_spec) == 72, "RpEmuAPI.get_video_spec offset drift");
static_assert(offsetof(RpEmuAPI, get_audio_spec) == 80, "RpEmuAPI.get_audio_spec offset drift");
static_assert(offsetof(RpEmuAPI, get_state) == 88, "RpEmuAPI.get_state offset drift");
static_assert(offsetof(RpEmuAPI, copy_audio) == 96, "RpEmuAPI.copy_audio offset drift");
static_assert(offsetof(RpEmuAPI, serialize) == 104, "RpEmuAPI.serialize offset drift");
static_assert(offsetof(RpEmuAPI, deserialize) == 112, "RpEmuAPI.deserialize offset drift");
static_assert(offsetof(RpEmuAPI, set_config_bitmask) == 120, "RpEmuAPI.set_config_bitmask offset drift");
static_assert(offsetof(RpEmuAPI, set_config_int) == 128, "RpEmuAPI.set_config_int offset drift");
static_assert(offsetof(RpEmuAPI, set_config_float) == 136, "RpEmuAPI.set_config_float offset drift");
static_assert(offsetof(RpEmuAPI, set_config_bool) == 144, "RpEmuAPI.set_config_bool offset drift");
static_assert(offsetof(RpEmuAPI, set_config_string) == 152, "RpEmuAPI.set_config_string offset drift");
static_assert(offsetof(RpEmuAPI, get_config_string) == 160, "RpEmuAPI.get_config_string offset drift");


#ifdef __cplusplus
}
#endif
