// @generated by api_gen - DO NOT EDIT. Regenerate with scripts/gen_bindings.sh.

#pragma once

#include <assert.h>
#include <stddef.h>
#include <flowi/core/string.h>

#define RP_PLUGIN_INFO_VERSION 1

#ifdef __cplusplus
extern "C" {
#endif

// Replay's plugin metadata: the nullptr-terminated tag array every plugin type
// publishes to describe itself (display name, description, version, author,
// menu placement, hotkey, ...). Tag values are always strings; the tag id says
// what the string means.
//
// The type is replay's, not flowi's — flowi's VFS plugin vtable carries it as a
// pointer-only extern-opaque and never dereferences it. The visibility and
// tag-array macros live in the hand-written <replay/plugin_info.h>.
// What a tag's string value means. Ids are spaced at 0x10000 intervals so each
// category can grow without renumbering the ones after it.
typedef enum RpPluginTag {
    // Display name shown to users.
    RpPluginTag_UserName = 0x00000,
    // Long description of plugin functionality.
    RpPluginTag_Description = 0x10000,
    // Label for UI buttons.
    RpPluginTag_ButtonName = 0x20000,
    // Menu location (e.g. "Tools/Debug").
    RpPluginTag_MenuPath = 0x30000,
    // Plugin version string (e.g. "1.0.0").
    RpPluginTag_Version = 0x40000,
    // Author name(s).
    RpPluginTag_Author = 0x50000,
    // Category (Debug, Visualization, System, ...).
    RpPluginTag_Category = 0x60000,
    // Icon path or name.
    RpPluginTag_Icon = 0x70000,
    // Keyboard shortcut (e.g. "Ctrl+Shift+M").
    RpPluginTag_Hotkey = 0x80000,
    // Load on startup ("1" or "0").
    RpPluginTag_AutoLoad = 0x90000,
} RpPluginTag;

// One tag entry. A plugin publishes an array of these terminated by a zeroed
// entry (`RP_PLUGIN_TAG_END`), which a reader finds by its null `value` data —
// the array carries no count.
typedef struct RpPluginInfo {
    // Tag value (string).
    FlString value;
    // Tag type.
    RpPluginTag tag;
} RpPluginInfo;

// Layout pins - the IDL-computed layout of the types above,
// checked against what this compiler produces.
static_assert(sizeof(RpPluginInfo) == 24, "RpPluginInfo size drift");
static_assert(offsetof(RpPluginInfo, value) == 0, "RpPluginInfo.value offset drift");
static_assert(offsetof(RpPluginInfo, tag) == 16, "RpPluginInfo.tag offset drift");


#ifdef __cplusplus
}
#endif
